import tkinter as tk
import uteis

janela = tk.Tk()
janela.title('Calculadora')
visor = tk.Entry(janela,width=50,borderwidth=5)
visor.grid(row=0,column=0,columnspan=4,pady=10,padx=10)
botao_percent = tk.Button(janela,text='%',width=6,height=3,padx=20,pady=10, command=lambda: uteis.porcentagem(visor))
botaoCE = tk.Button(janela,text='CE',width=6,height=3,padx=20,pady=10,command=lambda:uteis.delete(visor))
botaoC = tk.Button(janela,text='C',width=6,height=3,padx=20,pady=10,command=lambda:uteis.delete(visor))
botao_back = tk.Button(janela,text='<',width=6,height=3,padx=20,pady=10, command=lambda: uteis.back(visor))
botao1 = tk.Button(janela,text='1',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('1',visor))
botao2 = tk.Button(janela,text='2',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('2',visor))
botao3 = tk.Button(janela,text='3',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('3',visor))
botao4 = tk.Button(janela,text='4',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('4',visor))
botao5 = tk.Button(janela,text='5',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('5',visor))
botao6 = tk.Button(janela,text='6',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('6',visor))
botao7 = tk.Button(janela,text='7',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('7',visor))
botao8 = tk.Button(janela,text='8',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('8',visor))
botao9 = tk.Button(janela,text='9',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('9',visor))
botao0 = tk.Button(janela,text='0',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('0',visor))
botaox = tk.Button(janela,text='x',width=6,height=3,padx=20,pady=10, command=lambda: uteis.multiplicar(visor))
botao_menos = tk.Button(janela,text='-',width=6,height=3,padx=20,pady=10, command=lambda: uteis.subtrair(visor))
botao_mais = tk.Button(janela,text='+',width=6,height=3,padx=20,pady=10, command=lambda: uteis.somar(visor))
botao_igual = tk.Button(janela,text='=',width=6,height=3,padx=20,pady=10, command=lambda: uteis.igual(visor))
botao_ponto = tk.Button(janela,text='.',width=6,height=3,padx=20,pady=10, command=lambda: uteis.add('.',visor))
botao_divisao = tk.Button(janela,text='/',width=6,height=3,padx=20,pady=10, command=lambda: uteis.dividir(visor))

botao_percent.grid(row=1,column=0)
botaoCE.grid(row=1,column=1)
botaoC.grid(row=1,column=2)
botao_back.grid(row=1,column=3)

botao7.grid(row=2,column=0)
botao8.grid(row=2,column=1)
botao9.grid(row=2,column=2)
botaox.grid(row=2,column=3)

botao4.grid(row=3,column=0)
botao5.grid(row=3,column=1)
botao6.grid(row=3,column=2)
botao_menos.grid(row=3,column=3)

botao1.grid(row=4,column=0)
botao2.grid(row=4,column=1)
botao3.grid(row=4,column=2)
botao_mais.grid(row=4,column=3)

botao0.grid(row=5,column=0)
botao_ponto.grid(row=5,column=1)
botao_divisao.grid(row=5,column=2)
botao_igual.grid(row=5,column=3)

janela.mainloop()